### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by TheROcraft** [Gamorize/website#1]
UPDATEEEEEEE   my Roblox Profile picture
![therocraft](https://github.com/user-attachments/assets/586b2551-fc32-4e15-9797-b2219a7db0fb)

**Comment by TRC-Loop** [comment]
We are going to fix this ASAP. The Change will be released before 7th December 2024, 11:45. Thank you for your patience.

**Comment by TRC-Loop** [comment]
Fixed with #7271798

**Comment by TRC-Loop** [comment]
Will be uploaded to the Server now.
